Controllers/VentaController.cs
using Agroservicio.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;

namespace Agroservicio.Controllers
{
    public class VentaController : Controller
    {
        private readonly DbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public VentaController(DbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }


        public IActionResult SeleccionarCliente(int id)
        {
            HttpContext.Session.SetString("ClienteCarrito", JsonConvert.SerializeObject(id));

            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
            var productosDetalles = new List<object>();
            #region Validacion Cliente Seleccionado

            var ClienteCarrito = HttpContext.Session.GetString("ClienteCarrito");
            if (ClienteCarrito == null)
            {
                ViewBag.Clientes = _context.Cliente.ToList();
                return View(productosDetalles);
            }
            var IdClienteCarrito = JsonConvert.DeserializeObject<int>(ClienteCarrito);

            ViewBag.ClienteCarrito = _context.Cliente.Find(IdClienteCarrito);
            ViewBag.ListaDireccionCliente = _context.DireccionCliente.Where(x => x.IdCliente == IdClienteCarrito).ToList();

            #endregion

            #region Validacion Productos Agregados
            // Verificar si existe la sesión con la clave "Productos"
            var sessionProductos = HttpContext.Session.GetString("Productos");


            if (string.IsNullOrEmpty(sessionProductos))
            {
                return View(productosDetalles);
            }

            var ProductosAgregados = JsonConvert.DeserializeObject<List<Producto>>(sessionProductos);
            if (ProductosAgregados != null)
            {
                foreach (var item in ProductosAgregados)
                {
                    var detallesProducto = (from Producto in _context.Producto
                                            join BaseProducto in _context.BaseProducto on Producto.IdBaseProducto equals BaseProducto.Id
                                            join Empaque in _context.EmpaqueProducto on Producto.IdEmpaqueProducto equals Empaque.Id
                                            join Marca in _context.Marca on BaseProducto.IdMarca equals Marca.Id
                                            join TipoProducto in _context.TipoProducto on BaseProducto.IdTipoProducto equals TipoProducto.Id
                                            join GrupoTipoProducto in _context.GrupoTipoProducto on TipoProducto.IdGrupoTipoProducto equals GrupoTipoProducto.Id
                                            where Producto.Id == item.Id
                                            select new
                                            {
                                                Precio = Producto.Precio,
                                                RutaImagen = Producto.RutaImagen,
                                                ProductoExistencia = Producto.Existencia,
                                                ProductoId = Producto.Id,
                                                Nombre = BaseProducto.Nombre,
                                                EmpaqueNombre = Empaque.Nombre,
                                                Marca = Marca.Nombre, // Añadiendo este si es necesario
                                                TipoProducto = TipoProducto.Nombre, // Añadiendo este si es necesario
                                                GrupoTipoProducto = GrupoTipoProducto.Nombre,
                                                Cantidad = item.Existencia

                                            })
                                          .FirstOrDefault();

                    if (detallesProducto != null)
                    {
                        productosDetalles.Add(detallesProducto);
                    }
                }
            }
            #endregion
            return View(productosDetalles);
        }


        [HttpPost]
        public IActionResult BuscarProducto(string busqueda)
        {
            var productosDetalles = new List<object>();

            var Busqueda = _context.BaseProducto.Where(x => x.Nombre.Contains(busqueda)).ToList();

            foreach (var item in Busqueda)
            {
                var detalleProducto = (from Producto in _context.Producto
                                       join BaseProducto in _context.BaseProducto on Producto.IdBaseProducto equals BaseProducto.Id
                                       join Empaque in _context.EmpaqueProducto on Producto.IdEmpaqueProducto equals Empaque.Id
                                       join Marca in _context.Marca on BaseProducto.IdMarca equals Marca.Id
                                       join TipoProducto in _context.TipoProducto on BaseProducto.IdTipoProducto equals TipoProducto.Id
                                       join GrupoTipoProducto in _context.GrupoTipoProducto on TipoProducto.IdGrupoTipoProducto equals GrupoTipoProducto.Id
                                       where BaseProducto.Id == item.Id
                                       select new
                                       {
                                           ProductoPrecio = Producto.Precio,
                                           RutaImagen = Producto.RutaImagen,
                                           ProductoExistencia = Producto.Existencia,
                                           ProductoId = Producto.Id,
                                           BaseProductoNombre = BaseProducto.Nombre,
                                           EmpaqueNombre = Empaque.Nombre,
                                           MarcaNombre = Marca.Nombre, // Añadiendo este si es necesario
                                           TipoProductoNombre = TipoProducto.Nombre, // Añadiendo este si es necesario
                                           GrupoTipoProductoNombre = GrupoTipoProducto.Nombre // Añadiendo este si es necesario
                                       })
                                       .ToList();

                if (detalleProducto != null)
                {
                    productosDetalles.AddRange(detalleProducto);
                }
            }

            return PartialView("_ResultadosBusquedaPartial", productosDetalles);
        }
        [HttpPost]
        public JsonResult SeleccionarDireccion(int IdDireccion)
        {
            HttpContext.Session.SetString("IdDireccionCliente", JsonConvert.SerializeObject(IdDireccion));

            return Json(new { success = true, message = "Dirección seleccionada" });
        }


        [HttpPost]
        public IActionResult InsertarProducto(List<Producto> DatosSeleccionados)
        {
            try
            {
                // Obtener la lista de productos existente de la sesión
                var sessionProductos = HttpContext.Session.GetString("Productos");

                if (sessionProductos == null)
                {
                    HttpContext.Session.SetString("Productos", JsonConvert.SerializeObject(DatosSeleccionados));
                    return Json(new { Message = "Producto agregado", success = true });
                }

                var productosAgregadosAnterior = JsonConvert.DeserializeObject<List<Producto>>(sessionProductos);
                productosAgregadosAnterior.AddRange(DatosSeleccionados);
                HttpContext.Session.SetString("Productos", JsonConvert.SerializeObject(productosAgregadosAnterior));
                return Json(new { Message = "Producto agregado", success = true });
            }
            catch (System.Exception Error)
            {
                return Json(new { Error = Error.Message, success = false });
            }
        }
        public IActionResult RegistrarVenta()
        {
            //Obtener los datos guardados de las sessiones generadas
            var IdDireccionCliente = HttpContext.Session.GetString("IdDireccionCliente");

            if (IdDireccionCliente == null)
            {
                TempData["Error"] = "Si";
                TempData["Mensaje"] = "Seleccione una direccion del cliente";
                return RedirectToAction("Index");
            }
            int IdDireccion = JsonConvert.DeserializeObject<int>(IdDireccionCliente);

            var sessionProductos = HttpContext.Session.GetString("Productos");
            var ClienteCarrito = HttpContext.Session.GetString("ClienteCarrito");

            if (sessionProductos != null && ClienteCarrito != null) {
                var ProductosAgregados = JsonConvert.DeserializeObject<List<Producto>>(sessionProductos);
                var IdClienteCarrito = JsonConvert.DeserializeObject<int>(ClienteCarrito);


                var productosDetalles = new List<object>();
                if (ProductosAgregados != null)
                {
                    foreach (var item in ProductosAgregados)
                    {
                        var detallesProducto = (from Producto in _context.Producto
                                                join BaseProducto in _context.BaseProducto on Producto.IdBaseProducto equals BaseProducto.Id
                                                join Empaque in _context.EmpaqueProducto on Producto.IdEmpaqueProducto equals Empaque.Id
                                                join Marca in _context.Marca on BaseProducto.IdMarca equals Marca.Id
                                                join TipoProducto in _context.TipoProducto on BaseProducto.IdTipoProducto equals TipoProducto.Id

Views/Venta/DashboardVenta.cshtml
<title>Client Sales Dashboard</title>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="content-wrapper">
    
    <section class="content-header">

    </section>

   
        <div class="row">
            <div class="container">
                <h1 class="my-4 text-center">Reporte de ventas por cliente</h1>
                <div class="row">
                    <div class="col-md-12">
                        <canvas id="salesChart"></canvas>
                    </div>
                </div>
            </div>

            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    const ctx = document.getElementById('salesChart').getContext('2d');
                    const data = [
                    { label: "Cliente 1", data: 1500 },
                    { label: "Cliente 2", data: 1800 },
                    { label: "Cliente 3", data: 2100 },
                    { label: "Cliente 4", data: 2400 },
                    { label: "Cliente 5", data: 2700 },
                    { label: "Cliente 6", data: 3000 },
                    { label: "Cliente 7", data: 1650 },
                    { label: "Cliente 8", data: 1950 },
                    { label: "Cliente 9", data: 2250 },
                    { label: "Cliente 10", data: 2550 }
                    ];

                    const labels = data.map(item => item.label);
                    const salesData = data.map(item => item.data);
                    const backgroundColors = salesData.map(value => value < 1500 ? 'rgba(255, 99, 132, 0.2)' : value < 2250 ? 'rgba(54, 162, 235, 0.2)' : 'rgba(75, 192, 192, 0.2)');
                    const borderColors = salesData.map(value => value < 1500 ? 'rgba(255, 99, 132, 1)' : value < 2250 ? 'rgba(54, 162, 235, 1)' : 'rgba(75, 192, 192, 1)');

                    const salesChart = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: labels,
                            datasets: [{
                                label: 'Ventas',
                                backgroundColor: backgroundColors,
                                borderColor: borderColors,
                                borderWidth: 1,
                                data: salesData
                            }]
                        },
                        options: {
                            responsive: true,
                            scales: {
                                y: {
                                    beginAtZero: true,
                                    max: 3000
                                }
                            }
                        }
                    });
                });
            </script>

        </div>
 
    <!-- /.content -->
</div>

Views/Venta/ReporteVentas.cshtml
@model IEnumerable<Factura>

@{
    ViewData["Title"] = "Facturas";
    var lineasFactura = ViewBag.LineasFactura as IEnumerable<LineaFactura>;
    var ventasPorCliente = ViewBag.VentasPorCliente;
}

<div class="container">
    <h1 class="my-4">Dashboard de Ventas</h1>
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Ventas por Cliente</h5>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Cliente</th>
                                <th>Total Ventas</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var venta in ventasPorCliente)
                            {
                                <tr>
                                    <td>@venta.IdCliente</td>
                                    <td>@venta.TotalVentas.ToString("C")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <h1 class="my-4">Listado de Facturas</h1>
    <div class="row">
        @foreach (var factura in Model)
        {
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header">
                        <h5>Factura #@factura.Id</h5>
                        <p><strong>Cliente:</strong> @factura.IdCliente</p>
                        <p><strong>Fecha:</strong> @factura.Fecha.ToString("dd/MM/yyyy")</p>
                        <p><strong>Total:</strong> @factura.Total.ToString("C")</p>
                        <p><strong>Dirección:</strong> @factura.DireccionCliente?.Direccion </p>
                    </div>
                    <div class="card-body">
                        <h6>Líneas de Factura:</h6>
                        <ul class="list-group">
                            @foreach (var linea in lineasFactura.Where(lf => lf.IdFactura == factura.Id))
                            {
                                <li class="list-group-item">
                                    <p><strong>Producto:</strong> @linea.Producto.BaseProducto.Nombre</p>
                                    <p><strong>Cantidad:</strong> @linea.Cantidad</p>
                                    <p><strong>Precio:</strong> @linea.Precio.ToString("C")</p>
                                    <p><strong>Subtotal:</strong> @linea.SubTotal.ToString("C")</p>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Venta/_ResultadosBusquedaPartial.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resultados de Búsqueda</title>
    <style>
        .checkboxSeleccion {
            width: 15px; /* Ajusta el ancho */
            height: 15px; /* Ajusta la altura */
            /* Para mejorar la accesibilidad y mantener la calidad visual */
            transform: scale(1.5); /* Ajusta el factor de escala según sea necesario */
            -webkit-transform: scale(1.5); /* Soporte para navegadores webkit */
            -moz-transform: scale(1.5); /* Soporte para Firefox */
            -o-transform: scale(1.5); /* Soporte para Opera */
            -ms-transform: scale(1.5); /* Soporte para Internet Explorer */
            margin: 10px; /* Ajusta el margen según sea necesario */
        }
    </style>
 
</head>
<body>
    <div class="modal-header">
        <h5 class="modal-title">Resultados de Búsqueda</h5>
        <div class="ml-auto">
            <button class="btn btn-primary" onclick="MostrarIdSeleccionados()">Agregar <i class="fa fa-cart-plus" aria-hidden="true"></i></button>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th style="text-align:center">Nombre</th>
                <th style="text-align:center">Imagen</th>
                <th style="text-align:center">Precio</th>
                <th style="text-align:center">Existencia</th>
                <th style="text-align:center">Cantidad</th>
                <th style="text-align:center">Selección</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var Item in Model)
            {
                var IdCantidad = "CantidadProducto" + Item.ProductoId;

                <tr>
                    <td style="text-align:center">@Item.BaseProductoNombre @Item.EmpaqueNombre Marca:@Item.MarcaNombre</td>
                    <td style="text-align:center">
                        @if (Item.RutaImagen != null)
                        {
                            <!-- Agrega un botón para mostrar la imagen como popover -->
                            <button type="button" class="btn btn-default" data-toggle="popover" title="Imagen" data-content="<img src='/ImagenesProductos/@Item.RutaImagen' class='img-fluid' alt='Product Image'>">
                                <i class="fa fa-file-image-o" aria-hidden="true"></i>
                            </button>
                        }
                        else
                        {
                            <p>Sin imagen</p>
                        }
                    </td>
                    <td style="text-align:center">Q @Item.ProductoPrecio </td>
                    <td style="text-align:center">@Item.ProductoExistencia</td>
                    @if (Item.ProductoExistencia == 0)
                    {
                        <td style="text-align:center">
                            <p>No hay existencia disponible</p>
                        </td>
                        <td style="text-align:center">
                        </td>
                    }
                    else
                    {
                        <td style="text-align:center">
                            <input type="number" id="@IdCantidad" disabled />
                        </td>
                        <td style="text-align:center">
                            <input type="checkbox" class="checkboxSeleccion" id="@Item.ProductoId" data-existencia="@Item.ProductoExistencia" onchange="ValidarSeleccion(this, '@Item.ProductoExistencia')">
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
    <script>
        var Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000
        });
        function MostrarIdSeleccionados() {
            var DatosSeleccionados = [];
            var valid = true;

            $('.checkboxSeleccion:checked').each(function () {
                var idProducto = $(this).attr('id');
                var cantidad = parseInt($('#CantidadProducto' + idProducto).val());
                var existencia = parseInt($(this).data('existencia'));

                if (cantidad > existencia) {
                    Toast.fire({
                        icon: 'error',
                        title: 'La cantidad ingresada para el producto con ID ' + idProducto + ' excede la existencia disponible.'
                    });
                    valid = false;
                    return false;
                }

                if (cantidad > 0) {
                    DatosSeleccionados.push({ Id: idProducto, Existencia: cantidad });
                }
                else {
                    Toast.fire({
                        icon: 'error',
                        title: 'Hay  lineas seleccionadas sin indicar cantidad'
                    });

                    valid = false;
                    return false;
                }
            });
            if (valid) {
                if (DatosSeleccionados.length === 0) {
                    Toast.fire({
                        icon: 'error',
                        title: 'No hay lineas seleccionadas'
                    });
                    return false;
                }
                $.ajax({
                    url: '@Url.Action("InsertarProducto", "Venta")',
                    type: 'POST',
                    data: {
                        DatosSeleccionados
                    },
                    success: function (result) {

                        Toast.fire({
                            icon: 'success',
                            title: result.message
                        })
                        // Esperar medio segundo antes de recargar la página
                        setTimeout(function () {
                            window.location.reload();
                        }, 500);
                    },
                    error: function (xhr, status, error) {
                        swal({
                            title: "Error",
                            text: "Ocurrió un error al realizar la solicitud.",
                            type: "error"
                        });
                    }
                });
            }
        }

        function ValidarSeleccion(checkbox, existencia) {
            var idProducto = checkbox.id;
            var cantidadInput = $('#CantidadProducto' + idProducto);
            if (checkbox.checked) {
                cantidadInput.prop('disabled', false);
            } else {
                cantidadInput.prop('disabled', true);
                cantidadInput.val('');
            }
        }

        $(document).ready(function () {
            $('[data-toggle="popover"]').popover({
                html: true,
                trigger: 'hover'
            });

            $('.checkboxSeleccion').each(function () {
                ValidarSeleccion(this, $(this).data('existencia'));
            });
        });
    </script>
</body>
</html>